# Generated by Django 2.2.16 on 2022-03-06 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Категория')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Введены неправильные знаки!')])),
            ],
            options={
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='comment on review')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='year of writing')),
            ],
            options={
                'db_table': 'comment on review',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Жанр')),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='review of title')),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='score')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='year of writing')),
            ],
            options={
                'db_table': 'review for title',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название Произведения')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)])),
                ('description', models.TextField(blank=True, max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.Categories')),
                ('genre', models.ManyToManyField(related_name='genre', to='reviews.Genres')),
            ],
            options={
                'db_table': 'title',
                'ordering': ('name',),
            },
        ),
    ]
